name: app
description: Demonstrates how to use the fl_video plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_video:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
