name: app
description: Demonstrates how to use the fl_video plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  fl_video:
    path: ../
  flutter_waya: ^1.15.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true