name: fl_video
description: For the video_Player control panel, add Cupertino and Material styles
version: 1.3.0
repository: https://github.com/Wayaer/fl_video.git

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  video_player: ^2.7.0
  wakelock_plus: ^1.0.0+3

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
