name: fl_video
description: For the video_Player control panel, add Cupertino and Material styles
version: 0.0.3
homepage: https://github.com/Wayaer/fl_video

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  video_player: ^2.4.2
  wakelock: ^0.6.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
